name: tudor saitoc
url: http://tudr.co
description: kid is saying bah

permalink: /themes/:title/

highlighter: pygments
paginate: 20

markdown: rdiscount
rdiscount:
    extensions: ['smart']

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile', 'vendor']
